name: nawa_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

flutter:
  uses-material-design: true

assets:
  - .env

dependencies:
  flutter:
    sdk: flutter
  firebase_core_web: ^2.17.2
  firebase_auth_web: ^5.12.2
  firebase_storage_web: ^3.9.9
  firebase_messaging_web: ^3.8.9
  firebase_analytics_web: ^0.5.7+9
  firebase_performance_web: ^0.1.6+9
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  firebase_analytics: ^11.0.1
  firebase_performance: ^0.10.0+1
  google_mobile_ads: ^5.1.0
  flutter_secure_storage: ^9.2.2
  universal_html: ^2.2.4
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  flutter_localization: ^0.2.0
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0