// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlSs-rwemEFsRzSE6OvbZp_uuxjvuCeiw',
    appId: '1:828091702220:web:f495370b31f220de99db69',
    messagingSenderId: '828091702220',
    projectId: 'nawa-flutter-app',
    authDomain: 'nawa-flutter-app.firebaseapp.com',
    storageBucket: 'nawa-flutter-app.appspot.com',
    measurementId: 'G-84G7WP0J3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASYYUy2MLRzTVM-RGXCsYTrJxlYmTebM4',
    appId: '1:828091702220:android:64e452420c7d0bc799db69',
    messagingSenderId: '828091702220',
    projectId: 'nawa-flutter-app',
    storageBucket: 'nawa-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbMvd6MZvz6y8nQ5sjCG27_mPOR5Sfhc0',
    appId: '1:828091702220:ios:86e97e3447d0f0f499db69',
    messagingSenderId: '828091702220',
    projectId: 'nawa-flutter-app',
    storageBucket: 'nawa-flutter-app.appspot.com',
    iosBundleId: 'com.example.nawaFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbMvd6MZvz6y8nQ5sjCG27_mPOR5Sfhc0',
    appId: '1:828091702220:ios:86e97e3447d0f0f499db69',
    messagingSenderId: '828091702220',
    projectId: 'nawa-flutter-app',
    storageBucket: 'nawa-flutter-app.appspot.com',
    iosBundleId: 'com.example.nawaFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlSs-rwemEFsRzSE6OvbZp_uuxjvuCeiw',
    appId: '1:828091702220:web:cf1b79a9ab7272fb99db69',
    messagingSenderId: '828091702220',
    projectId: 'nawa-flutter-app',
    authDomain: 'nawa-flutter-app.firebaseapp.com',
    storageBucket: 'nawa-flutter-app.appspot.com',
    measurementId: 'G-ZPCVCSTEL2',
  );
}
